### ISSUE TITLE
move to coder/images

### ISSUE THREAD

**Issue by matifali** [coder/images#275]
I am unfamiliar with why these images are called `enterprise-xxx`. We should probably rename the repo and images to `coder/images`. 
We can keep the legacy images on dockerhub and publish the new ones ghcr.io

The idea is to have something like [`coder/modules`](https://github.com/coder/modules) and [`coder/templates`](https://github.com/coder/templates) and integrate with https://registry.coder.com where we can list images too. We can also accept community contributions for templates and images as we do with modules and list on our registry. 

cc: @bpmct

**Comment by johnstcn** [comment]
While we're at it, I'd like to change the naming scheme:

- `images/base/ubuntu.Dockerfile` -> `ubuntu:base`
- `images/minimal/ubuntu.Dockerfile` -> `ubuntu:minimal`
- `images/$IMAGE/$DISTRO.Dockerfile` -> `$DISTRO:$IMAGE`

**Comment by matifali** [comment]
Hi, @PraveenkumarLilly. To use GPU, you also need a few other steps; please look at the deep learning templates and the source code for dockerdl images below to get the idea.
1. https://github.com/matifali/coder-templates
2. https://github.com/matifali/dockerdl

**Comment by PraveenkumarLilly** [comment]
Hi @ericpaulsen,
Sure, Eric I'll do that

Thanks.

**Comment by matifali** [comment]
> While we're at it, I'd like to change the naming scheme:
> 
> * `images/base/ubuntu.Dockerfile` -> `ubuntu:base`
> * `images/minimal/ubuntu.Dockerfile` -> `ubuntu:minimal`
> * `images/$IMAGE/$DISTRO.Dockerfile` -> `$DISTRO:$IMAGE`
> 
> This might entail some shuffling things around on-disk.

@jatcod3r, We are going to adopt the above convention for naming new and old images.

**Comment by bpmct** [comment]
I like the new convention 👍🏼

**Comment by bpmct** [comment]
I renamed the project.

**Comment by matifali** [comment]
@johnstcn, do you also want images to be renamed or only the directory structure?

For images `codercom/enterprise-base` --> `codercom/base`?

**Comment by johnstcn** [comment]
> [@johnstcn](https://github.com/johnstcn), do you also want images to be renamed or only the directory structure?
> 
> For images `codercom/enterprise-base` --> `codercom/base`?

I'm fine with keeping the current names of the published images.
Renaming them would be a bit more involved and require communications.
If we really feel like we want to rename the published images as well, we could dual-publish under both naming conventions with a deprecation period.

**Comment by bpmct** [comment]
Huge fan of dual-publishing so we have a nice clean image for new users/examples. Down the road, we could use a motd or something to let people know we'll stop dual-publishing

**Comment by matifali** [comment]
Extracted renaming to a separate issue and closing this as completed.
